name: Build

on:
  workflow_dispatch:
    inputs:
      angleVersion:
        description: "Angle version"
        required: true
        type: string
jobs:
  build-linux-x64:
    uses: ./.github/workflows/linux-x64.yml
    with:
      angleVersion: ${{ inputs.angleVersion }}
    secrets: inherit

  build-windows-x64:
    uses: ./.github/workflows/windows-x64.yml
    with:
      angleVersion: ${{ inputs.angleVersion }}
    secrets: inherit
