name: windows-x64

on:
  workflow_call:
    inputs:
      angleVersion:
        required: true
        type: string

jobs:
  build-windows-x64:
    runs-on: windows-2022
    steps:
      - name: Pack
        shell: bash
        run: |
          sleep 200
          mkdir angle-windows-x64
          echo "Hello Windows "${{ angleVersion }} >> angle-windows-x64/windows-x64.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angle-windows-x64
          path: angle-windows-x64
